diff update_submit.py ~/Dropbox/classes/scripts/update_submit.py
diff update_course.py ~/Dropbox/classes/scripts/
diff update_bash_env.sh ~/Dropbox/classes/scripts/
diff tinkeracademy.py ~/Dropbox/classes/scripts/
diff submit_course.py ~/Dropbox/classes/scripts/
diff restart_dropbox.sh ~/Dropbox/classes/scripts/
diff reset_submit.py ~/Dropbox/classes/scripts/
diff reset_minecraft_world.sh ~/Dropbox/classes/scripts/
diff reset_minecraft.py ~/Dropbox/classes/scripts/
diff post_update_hook.py ~/Dropbox/classes/scripts/
diff fix_odt.py ~/Dropbox/classes/scripts/
diff fix_it.py ~/Dropbox/classes/scripts/
diff poweroff.py ~/Dropbox/classes/scripts/
